language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 1872c63f5246746a03551c9f430e816b2338f83b
  local_dir: build
  on:
    branch: master
    