language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $4eb3bd56d80a6c1803cbb832520c84aa03e488fa
  local_dir: build
  on:
    branch: master